#!/bin/bash

# Step 1: Displaying a message indicating the start of system setup
echo "Starting your system-setup soon!"
sleep 1

# Step 2: Updating package repositories
echo "Running: apt update"
sudo apt update

# Step 3: Installing Apache web server
echo "Installing apache2"
sudo apt-get install apache2

# Step 4: Installing PHP
echo ""
echo "Installing php"
sudo apt-get purge 'php*'
sudo add-apt-repository ppa:ondrej/php
sudo apt update

# Step 5: Selecting PHP versions to install
echo ""
echo "Enter PHP versions to install (separated by spaces): "
read -a versions
echo ""

# Step 6: Installing selected PHP versions
for v in "${versions[@]}"; do
    echo ""
    echo "Installing PHP version $v"
    sudo apt-get install php$v php$v-mysql php$v-mbstring php$v-mcrypt php$v-bcmath php$v-xml php$v-gd php$v-zip php$v-curl php$v-fpm php$v-mongo php$v-redis -y
done

echo ""
echo "Installation of PHP versions ${versions[@]} completed!"

# Step 7: Installing Redis
echo ""
echo "Installing redis"
sudo apt update
sudo apt-get install build-essential tcl8.6
sudo apt install redis-server
sudo nano /etc/redis/redis.conf
sudo sed -i 's/^supervised.*/supervised systemd/' /etc/redis/redis.conf

# Step 8: Installing Composer
echo ""
echo "Installing composer"
sudo apt-get install curl
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

# Step 9: Installing Git
echo ""
echo "Installing git"
sudo apt install git


